name: user
home: https://github.com/bobchat/bobchat-platform
version: 0.1.0
description: User Service
sources:
  - https://github.com/bobchat/bobchat-platform
maintainers:
  - name: Sam Heutmaker
    email: samheutmaker@gmail.com
