apiVersion: v1
kind: Service
metadata:
  name: {{ template "bobchat-platform.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.component}}"
{{- if .Values.serviceAnnotations}}
  annotations:
{{ toYaml .Values.serviceAnnotations | indent 4 }}
      service: {{ .Release.Name }}-bobchat-platform.default:80
{{- end}}
spec:
  ports:
    - port: {{.Values.servicePort}}
      targetPort: {{.Values.containerPort}}
  selector:
    component: "{{.Release.Name}}-{{.Values.component}}"
  type: {{ default "ClusterIP" .Values.serviceType | quote }}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "bobchat-platform.fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.component}}"
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{.Release.Name}}-{{.Values.component}}"
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}-{{.Values.component}}"
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: "{{.Values.image}}:{{.Values.global.imageTag}}"
          imagePullPolicy: {{.Values.imagePullPolicy}}
          ports:
          - name: http
            containerPort: {{.Values.containerPort}}
          resources:
            requests:
              cpu: {{.Values.cpu}}
              memory: {{.Values.memory}}
            limits:
              cpu: {{.Values.cpu}}
              memory: {{.Values.memory}}
          env:
            - name: WORKFLOW_RELEASE
              value: {{.Release.Name | quote }}
            - name: NODE_ENV
              value: {{ default "" .Values.env.NODE_ENV | quote }}
            - name: MONGO_DB_HOST
              value: "{{ .Release.Name }}-mongodb.default.svc.cluster.local"
            - name: MONGO_DB_PORT
              value: {{ default "" .Values.env.MONGO_DB_PORT | quote}}
            - name: MONGO_DB_NAME
              value: {{ default "" .Values.env.MONGO_DB_NAME | quote}}
            - name: MONGO_DB_DATABASE
              value: {{ default "" .Values.env.MONGO_DB_DATABASE | quote}}
            - name: MONGO_DB_USER
              value: {{ default "" .Values.env.MONGO_DB_USER | quote}}
            - name: MONGO_DB_PASSWORD
              value: {{ default "" .Values.env.MONGO_DB_PASSWORD | quote}}
            - name: REDIS_HOST
              value: {{ default "" .Values.env.REDIS_HOST | quote}}
            - name: REDIS_PORT
              value: {{ default "" .Values.env.REDIS_PORT | quote}}